name: Flask Analytics

on:
  push:
    branches: [ "main" ]
#     tags: [ 'v*.*.*' ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

#     env:
#       VERSION_TAG: ${{ env.VERSION_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build the Docker image
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask_analytics:latest .
#         docker build -t ${{ secrets.DOCKER_USERNAME }}/flask_analytics:v{{ env.VERSION_TAG }} .

    - name: Publish the Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/flask_analytics:latest
#        docker push ${{ secrets.DOCKER_USERNAME }}/flask_analytics:v{{ env.VERSION_TAG }}
