name: Package Release Next Dev Iteration

on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: 1.0.0
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

#     env:
#       VERSION_TAG: ${{ env.VERSION_TAG }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
#     - name: Install dependencies
#       run: |
#         pip install --upgrade pip
#         pip install -r requirements.txt

    - name: Build the Docker image
      run: |
          docker build -t sb-analytics:latest .

    - name: Publish the Docker image
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u "smilebat96" --password-stdin
        docker tag sb-analytics:latest smilebat96/sb-analytics:latest
        docker push smilebat96/sb-analytics:latest
        
    - name: Build the Docker image With Version
      run: |
          docker build -t sb-analytics:'${{ github.event.inputs.version }}' .

    - name: Publish the Docker image
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u "smilebat96" --password-stdin
        docker tag sb-analytics:'${{ github.event.inputs.version }}' smilebat96/sb-analytics:'${{ github.event.inputs.version }}'
        docker push smilebat96/sb-analytics:'${{ github.event.inputs.version }}'
